CREATE DATABASE IF NOT EXISTS newproject;
USE newproject;

-- Table structure for table `permiso`

CREATE TABLE IF NOT EXISTS permiso (
    IDPERMISO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255)
);

-- Table structure for table `rol`
CREATE TABLE IF NOT EXISTS rol (
    IDROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- Table structure for table `rol_permiso`
CREATE TABLE IF NOT EXISTS rol_permiso (
    IDROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ROL_ID INT NOT NULL,
    PERMISO_ID INT NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES rol(IDROL),
    FOREIGN KEY (PERMISO_ID) REFERENCES permiso(IDPERMISO)
);


-- Table structure for table `usuario`
CREATE TABLE IF NOT EXISTS usuario (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL,
    PASSWORD TINYBLOB NOT NULL,
    ROL_ID INT DEFAULT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ROL_ID) REFERENCES rol(IDROL)
);

-- Table structure for table `cliente`
CREATE TABLE IF NOT EXISTS cliente (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(255),
    DIRECCION VARCHAR(255),
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES usuario(IDUSUARIO)
);

-- Table structure for table `pedido`
CREATE TABLE IF NOT EXISTS pedido (
    IDPEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    FECHAENTREGA DATETIME DEFAULT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID)
);

-- Table structure for table `venta`
CREATE TABLE IF NOT EXISTS venta (
    IDVENTA INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    PEDIDO_ID INT NOT NULL,
    CODIGO VARCHAR(255) NOT NULL,
    PRECIO_TOTAL DECIMAL(10,2) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES pedido(IDPEDIDO),
    FOREIGN KEY (USUARIO_ID) REFERENCES usuario(IDUSUARIO)
);

-- Table structure for table `metodo_pago`
CREATE TABLE IF NOT EXISTS metodo_pago (
    IDMETODO_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table structure for table `pago`
CREATE TABLE IF NOT EXISTS pago (
    IDPAGO INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    METODO_PAGO_ID INT NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL,
    ESTADO TINYINT NOT NULL,
    TRANSACCION_EXTERNA VARCHAR(255),
    FOREIGN KEY (VENTA_ID) REFERENCES venta(IDVENTA),
    FOREIGN KEY (METODO_PAGO_ID) REFERENCES metodo_pago(IDMETODO_PAGO)
);

-- Table structure for table `carrito`
CREATE TABLE IF NOT EXISTS carrito (
    IDCARRITO INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID)
);

-- Table structure for table `categoria`
CREATE TABLE IF NOT EXISTS categoria (
    CODCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table structure for table `producto`
CREATE TABLE IF NOT EXISTS producto (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    MARCA VARCHAR(100),
    DESCRIPCION TEXT,
    COSTO FLOAT NOT NULL,
    PRECIO_MIN DECIMAL(10,2) NOT NULL,
    PRECIO_MAX DECIMAL(10,2),
    STOCK INT NOT NULL,
    ESTADO TINYINT NOT NULL,
    IMAGEN VARCHAR(255),
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES categoria(CODCATEGORIA)
);

-- Table structure for table `producto_variante`
CREATE TABLE IF NOT EXISTS producto_variante (
    IDVARIANTE INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    TALLA VARCHAR(50),
    COLOR VARCHAR(50),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES producto(ID)
);


-- Table structure for table `carrito_detalle`
CREATE TABLE IF NOT EXISTS carrito_detalle (
    IDCARRITO_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    CARRITO_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (CARRITO_ID) REFERENCES carrito(IDCARRITO),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES producto_variante(IDVARIANTE)
);

-- Table structure for table `descuento`
CREATE TABLE IF NOT EXISTS descuento (
    IDDESCUENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    PORCENTAJE DECIMAL(5,2) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table structure for table `envio`
CREATE TABLE IF NOT EXISTS envio (
    IDENVIO INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    FECHA_ENVIO DATETIME DEFAULT NULL,
    ESTADO TINYINT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (VENTA_ID) REFERENCES venta(IDVENTA)
);

-- Table structure for table `notificacion`
CREATE TABLE IF NOT EXISTS notificacion (
    IDNOTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    MENSAJE TEXT NOT NULL,
    TIPO VARCHAR(50),
    LEIDO TINYINT DEFAULT 0,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID)
);

-- Table structure for table `pedido_detalle`
CREATE TABLE IF NOT EXISTS pedido_detalle (
    IDPEDIDO_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES pedido(IDPEDIDO),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES producto_variante(IDVARIANTE)
);

-- Table structure for table `producto_descuento`
CREATE TABLE IF NOT EXISTS producto_descuento (
    IDPRODUCTO_DESCUENTO INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    DESCUENTO_ID INT NOT NULL,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES producto(ID),
    FOREIGN KEY (DESCUENTO_ID) REFERENCES descuento(IDDESCUENTO)
);


-- Table structure for table `resena`
CREATE TABLE IF NOT EXISTS resena (
    IDRESENA INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO_ID INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    CALIFICACION INT NOT NULL,
    COMENTARIO TEXT,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES producto(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID)
);

-- Table structure for table `venta_detalle`
CREATE TABLE IF NOT EXISTS venta_detalle (
    IDVENTA_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES venta(IDVENTA),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES producto_variante(IDVARIANTE)
);

-- Table structure for table `wishlist`
CREATE TABLE IF NOT EXISTS wishlist (
    IDWISHLIST INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    NOMBRE VARCHAR(255) DEFAULT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(ID)
);

-- Table structure for table `wishlist_producto`
CREATE TABLE IF NOT EXISTS wishlist_producto (
    IDWISHLIST_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    WISHLIST_ID INT NOT NULL,
    PRODUCTO_VARIANTE_ID INT NOT NULL,
    FOREIGN KEY (WISHLIST_ID) REFERENCES wishlist(IDWISHLIST),
    FOREIGN KEY (PRODUCTO_VARIANTE_ID) REFERENCES producto_variante(IDVARIANTE)
);